---
sidebar: sidebar 
permalink: get-started/online_api_ref.html 
keywords: reference, api reference 
summary: Você pode acessar os detalhes das chamadas da API REST do Astra Control, incluindo os métodos HTTP, parâmetros de entrada e respostas. Essa referência completa é útil ao desenvolver aplicativos de automação usando a API REST. 
---
= Referência de API online
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode acessar os detalhes das chamadas da API REST do Astra Control, incluindo os métodos HTTP, parâmetros de entrada e respostas. Essa referência completa é útil ao desenvolver aplicativos de automação usando a API REST.


NOTE: A documentação de referência da API REST é fornecida atualmente com o Astra Control e está disponível on-line.

.Antes de começar
Você precisa de uma conta para Astra Control Center ou Astra Control Service.

.Passos
. Faça login no Astra usando suas credenciais de conta.
+
Acesse o seguinte site do Astra Control Service: link:https://astra.netapp.io["https://astra.netapp.io"^]

. Clique no ícone de figura no canto superior direito da página e selecione *Acesso à API*.
. Na parte superior da página, clique no URL exibido em *Documentação da API*.
. Forneça as credenciais da sua conta novamente, se solicitado.

